/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_noaa_messageapi_endpoints_BaseNativeEndpoint*/

#ifndef _Included_gov_noaa_messageapi_endpoints_BaseNativeEndpoint
#define _Included_gov_noaa_messageapi_endpoints_BaseNativeEndpoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_noaa_messageapi_endpoints_BaseNativeEndpoint
 * Method:    createNativeInstance
 * Signature: (Lgov/noaa/messageapi/containers/TaskMap;)J
 */
JNIEXPORT jlong JNICALL Java_gov_noaa_messageapi_endpoints_BaseNativeEndpoint_createNativeInstance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gov_noaa_messageapi_endpoints_BaseNativeEndpoint
 * Method:    releaseNativeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_noaa_messageapi_endpoints_BaseNativeEndpoint_releaseNativeInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
