/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_noaa_messageapi_transformations_NativeTransformation */

#ifndef _Included_gov_noaa_messageapi_transformations_NativeTransformation
#define _Included_gov_noaa_messageapi_transformations_NativeTransformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_noaa_messageapi_transformations_NativeTransformation
 * Method:    process
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_gov_noaa_messageapi_transformations_NativeTransformation_process
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_noaa_messageapi_transformations_NativeTransformation
 * Method:    create
 * Signature: (Ljava/util/Map;)J
 */
JNIEXPORT jlong JNICALL Java_gov_noaa_messageapi_transformations_NativeTransformation_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gov_noaa_messageapi_transformations_NativeTransformation
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_noaa_messageapi_transformations_NativeTransformation_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
