/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_noaa_messageapi_conditions_NativeCondition */

#ifndef _Included_gov_noaa_messageapi_conditions_NativeCondition
#define _Included_gov_noaa_messageapi_conditions_NativeCondition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_noaa_messageapi_conditions_NativeCondition
 * Method:    compare
 * Signature: (J)Z
 */
JNIEXPORT bool JNICALL Java_gov_noaa_messageapi_conditions_NativeCondition_compare
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_noaa_messageapi_conditions_NativeCondition
 * Method:    create
 * Signature: (Z;Z)J
 */
JNIEXPORT jlong JNICALL Java_gov_noaa_messageapi_conditions_NativeCondition_create
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     gov_noaa_messageapi_conditions_NativeCondition
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_noaa_messageapi_conditions_NativeCondition_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
